name: 'Terraform'

on:
  push:
    branches:
      - main
      - dev
      - staging
  pull_request:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-core:
    name: 'Terraform Core'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'infra/environments/core'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate and Plan Terraform
        uses: ./.github/actions/validate-and-plan-terraform
        with:
          pr_env: 'Core'
